### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by debug-ito** [hnakamur/FormatLink-Chrome#8]
Looks like keyboard shortcut was introduced by p-r #1, but removed at 823b542141fc42a49c931cfe46efe2e338a15dee. I wonder why. I'd really like to have keyboard shortcut.

**Comment by hnakamur** [comment]
I removed keyboard shortcut because it turns out that I don't use it.

Also there is a limitation in webextension API that you cannot get the selected link info with keyboard shortcut.

You may want to try another extension which has keyboard shortcut.
https://chrome.google.com/webstore/detail/copy-url-to-clipboard/miancenhdlkbmjmhlginhaaepbdnlllc

**Comment by debug-ito** [comment]
Thanks for the pointer.
Unfortunately, however, copy-url-to-clipboard does not support customizing the format. Also, its keyboard shortcut somehow didn't work in my browser (vivaldi 1.13.1008.40 for Linux 64-bit).

I understand the limitation. However, I always use this add-on to get the URL and the title of the current web page (the case 3 of "How to use" in the README.) There's no text selection involved. In that case, keyboard shortcut does work, right?

**Comment by hnakamur** [comment]
I added keyboard shortcuts again at
https://github.com/hnakamur/FormatLink-Chrome/commit/1c2691c0bbdf50e74b475b4b30bd5be26a493c97#diff-4b1eb3dc48c4e16d49db5b42298fe654
Sorry for being late.
